/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.client.engine.cio.*
import io.ktor.client.plugins.websocket.*
import io.ktor.websocket.*

import io.ktor.http.*
import org.msgpack.jackson.dataformat.MessagePackFactory

suspend fun main() {
    val client = HttpClient(CIO) {
        install(WebSockets)
    }
    println("Hello")

    val mapper = ObjectMapper(MessagePackFactory()).registerKotlinModule()
    client.ws(method = HttpMethod.Get, host = "127.0.0.1", port=9001, path = "/") {
        // send a message
        val bytes = mapper.writeValueAsBytes(PeerMessage.Greet)
        send(bytes)

        // receive a message
        for (frame in incoming) {
            val v = mapper.readValue(frame.data, PeerMessage::class.java)
            println("Received: ${v}")
        }
    }

    client.close()
}
