/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import Doc
import io.ktor.client.*
import io.ktor.client.engine.cio.*
import io.ktor.client.plugins.websocket.*
import io.ktor.websocket.*

import io.ktor.http.*

suspend fun main() {
    val client = HttpClient(CIO) {
        install(WebSockets)
    }
    println("Hello")
    var doc = Doc.fromString("local", 0.toUByte());
    client.ws(method = HttpMethod.Get, host = "127.0.0.1", port=9001, path = "/") {
        // send a message
        val bytes = PeerMessage.Greet.serialize();
        send(bytes)

        // receive a message
        for (frame in incoming) {
            val v = PeerMessage.deserialize(frame.data)
            when (v) {
                is PeerMessage.NewSession -> {
                    doc = v.doc;
                }

                is PeerMessage.Delete -> {
                    doc.delete(v.pid)
                }
                PeerMessage.Greet -> TODO()
                is PeerMessage.Insert -> {
                    doc.insert(v.pid, v.c)
                }
            }
            println("Doc state: ${doc.display()}")
        }
    }

    client.close()
}
